#
# (C) 2023, Roberto A. Foglietta <roberto.foglietta@gmail.com>
#           Released and re-licensed under the GPLv2 license terms.
#
# Copyright (c) 2023 robang74 (Roberto A. Foglietta)
#               2022-2023 olf (Olf0)
#               2017-2022 Petr Tsymbarovich (mentaljam / osetr)
#               2019-2022 Björn Bidar (Thaodan)
#               2020 Dmitry Gerasimov (dseight)
#               2019 Matti Viljanen (direc85)
#               2019 Miklós Márton (martonmiklos)
#               2018 elros34
#               2017 Christoph (inta)
#
################################################################################

name: build on tags

on:
  push:
    tags:
      - '*'
#     - 'v*[0-9]+.[0-9]+.*'
#     - '^[0-9]+.[0-9]+.*'
  workflow_dispatch:
    branches:
      - default

env:
  SFOS_RELEASE: 4.5.0.16

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Prepare
      run: mkdir -p RPMS
      
    - name: ARM64 build for ${{ env.ARCH }} on ${{ env.RELEASE }}
      env:
        ARCH: aarch64
        RELEASE: ${{ env.SFOS_RELEASE }}
      uses: robang74/github-sfos-apps-build@v0.1.4
      with:
        release: ${{ env.RELEASE }}
        arch: ${{ env.ARCH }}

    - name: ARMv7 build for ${{ env.ARCH }} on ${{ env.RELEASE }}
      env:
        ARCH: armv7hl
        RELEASE: ${{ env.SFOS_RELEASE }}
      uses: robang74/github-sfos-apps-build@v0.1.4
      with:
        release: ${{ env.RELEASE }}
        arch: ${{ env.ARCH }}

    - name: AMD86 build for ${{ env.ARCH }} on ${{ env.RELEASE }}
      env:
        ARCH: i486
        RELEASE: ${{ env.SFOS_RELEASE }}
      uses: robang74/github-sfos-apps-build@v0.1.4
      with:
        release: ${{ env.RELEASE }}
        arch: ${{ env.ARCH }}

    - name: Upload build results
      uses: actions/upload-artifact@v3
      with:
        name: RPMS build results
        path: RPMS

# RAF: creating a release has been disabled because I want to keep the last created tag
#    - name: Create release
#      if: contains(github.ref, 'release')
#      run: |
#        set -x
#        assets=()
#        for asset in RPMS/*.rpm; do
#          assets+=("-a" "$asset")
#        done
#        tag_name="${GITHUB_REF##*/}"
#        hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
